### ISSUE TITLE
怎么上传token

### ISSUE THREAD

**Issue by benpaodelang** [NextBoy/quill-image-extend-module#2]
用七牛上传图片怎么上传token

**Comment by NextBoy** [comment]
@benpaodelang 可以试试在change() 那里修改, 我没用过七牛云，七牛云是每次都要获取一个新token吗？
你试试在change函数里面改行不行，如果是要把token塞到头部，就设置xhr的头部，如果是要当做参数传递过去就塞到formData

**Comment by cyxuan0926** [comment]
你写的那个上传图片的组件 怎么解决跨域问题 服务端总是返回未登陆

**Comment by NextBoy** [comment]
@cyxuan0926 加下QQ920026184详细说明下问题
