### ISSUE TITLE
Upload error for response code 201

### ISSUE THREAD

**Issue by DeyLak** [NextBoy/quill-image-extend-module#4]
If my back-end for upload images returns code 201(created), instead of 200(success) the editor is showing uploading error. 
I think, it's better to have more flexible response codes configurations(in callbacks, may be), or at least, to treat 2** codes as success, as it is stated in the docs.

**Comment by NextBoy** [comment]
@DeyLak Thank you for your advice. I'm going to change it. #3

**Comment by NextBoy** [comment]
@DeyLak     That should be fine.
```
   xhr.onreadystatechange = function() {
        if (xhr.readyState === 4) {
            if (xhr.status === 200) {
                //success
            } else {
                //error
            }
        }
    }
```
