### ISSUE TITLE
当前项目可以按<script src="">的方式引入吗

### ISSUE THREAD

**Issue by neatstudio** [NextBoy/quill-image-extend-module#61]
要兼容旧一点的方案。不是纯VUE项目，所以需要这样的引入方式。不知道是否支持？

**Comment by huanhuanhome** [comment]
> 要兼容旧一点的方案。不是纯VUE项目，所以需要这样的约会方式。不知道是否支持？
解决了么？

**Comment by neatstudio** [comment]
已放弃，因为他有一个很大的问题。。。（只有自有格式，所有的外带格式全部无效了）
自用可以，非自用，则几乎无解

**Comment by Vetich** [comment]
没法用？还是怎么？

**Comment by neatstudio** [comment]
我放弃quill了。主要是因为quill转出来的格式和其他编辑器的格式不一致。暂时先放弃，后续再慢慢看

**Comment by Vetich** [comment]
好的吧，我按照script 引入



识别不了ImageExtend，还有解决方案，网上全都是vue得……
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"膘叔"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午5:27
收件人:&nbsp;"NextBoy/quill-image-extend-module"<quill-image-extend-module@noreply.github.com&gt;;
抄送:&nbsp;"王奇"<1961531928@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [NextBoy/quill-image-extend-module] 当前项目可以按<script src=""&gt;的方式引入吗 (#61)




我放弃quill了。主要是因为quill转出来的格式和其他编辑器的格式不一致。暂时先放弃，后续再慢慢看
